# mixer and swupd-client requires the xz compression type
# to be supported in bsdtar.
PACKAGECONFIG_append = " xz zstd"

# Since the format of the archives generated by mixer and
# the ones consumed by swupd-client must be identical
# configure the native tool the same way as it's done for target.
PACKAGECONFIG_append_class-native = "\
    ${@bb.utils.contains('DISTRO_FEATURES', 'xattr', 'xattr', '', d)} \
"
